version: '3.3'

services: 
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ${VOLUMES_PATH}/mongo:/data/db
    ports:
      - ${MONGO_OUT_PORT}:27017
    environment: 
      - MONGO_INITDB_DATABASE=${MONGODB_DBNAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
  redis:
    image: redis:alpine
    restart: always


  api:
    build: 
      context: ./
      dockerfile: ./packages/api/Dockerfile
    env_file: 
      - .env
    depends_on: 
      - mongo
      - redis

  client:
    build: 
      context: ./
      dockerfile: ./packages/client/Dockerfile
      args: 
        - REACT_APP_API_SERVER_HOST=${API_SERVER_HOST}
        - REACT_APP_API_SERVER_PORT=${API_SERVER_PORT}
        - REACT_APP_API_SERVER_PATH=${API_SERVER_PATH}
        - REACT_APP_SUBSCRIBE_SERVER_PATH=${SUBSCRIBE_SERVER_PATH}
    env_file: 
      - .env
    volumes: 
      - ${VOLUMES_PATH}/logs/client:/var/log/client_nginx


  nginx:
    image: nginx
    env_file:
      - .env
    ports: 
      - 80:80
      - 443:443
    command: /bin/bash -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes: 
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf.template
      - ./configs/nginx/${PROTOCOL_TYPE}.conf:/etc/nginx/conf.d/server.conf
      - ${VOLUMES_PATH}/logs/nginx:/var/log/nginx
      - ${SSL_PATH}:/etc/nginx/ssl
    depends_on: 
      - client
      - api
