version: '3.3'

services: 
  client:
    build: 
      context: ./
      dockerfile: ./packages/client/Dockerfile
    env_file: 
      - ./.env
    ports: 
      - 8080:8080
      - 8081:80
  nginx:
    image: nginx
    env_file:
      - .env
    ports: 
      - 80:80
    command: /bin/bash -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes: 
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf.template
    depends_on: 
      - client