version: '3.3'

services: 
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./volumes_data/mongo:/data/db
      - test_vol:/test_vol
    env_file:
      - .env
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_OUT_PORT}:8081
    env_file:
      - .env
    volumes: 
      - test_vol:/test_vol
  redis:
    image: redis:alpine
    ports:
      - "80:6379"
    restart: always

volumes: 
  test_vol:
  